#%RAML 1.0
title: ACME Banking AP
mediaType:
  - application/json
version: v1
protocols:
  - HTTP
  - HTTPS
description: |
  Base URI = URL final donde estara la app, mycompanu.com/api.

  This API offers access to persinal banking data, around customer, transactions ans accounts.
/accounts:
  get:
    displayName: get All Account Info
/customers:
  get:
    displayName: get All Customers Info
