#%RAML 1.0
title: ACME Banking API
description: |-
  This API offers access to personal banking data, around customers, transactions and accounts. Github Signed!
mediaType:
  - application/json
version: v1
protocols:
  - HTTPS
  - HTTP


/accounts:
  post:
    displayName: Create a new account
    responses:
      201:
      400:
        headers:
        body:
          example:
            type: Missing attribute
            title: Body structure incomplete
            detail: Body is missing the account id.
          

  
  /{account_id}:
    get:
      displayName: Get information for a specific account
      responses:
        200:
    put:
      displayName: Get information for a specific account
      responses:
        201:
    delete:
      displayName: Get information for a specific account
      responses:
        202:
        204:

/accounts/{account_id}/transactions:
  get:
    displayName:  Get all transactions for a specific account
    responses:
      200:

/customers:
  get:
    displayName: Get all customers in the bank
    responses:
      200:
  post:
    displayName: Create a new customer
    responses:
      201:
  
  /{customer_id}:
    get:
      displayName: Get information for a specific customer
      responses:
        200:

    patch:
      displayName: Update information for a specific customer
      responses:
        204:
    delete:
      displayName: Delete information for a specific customer
      responses:
        202:
        204:

/customers/{customer_id}/accounts:
  get:
    displayName: Get all accounts for a specific customer
    responses:
      200:
    

/transactions:
  post:
    displayName: Create a new transaction
    responses:
      201:
  /{transaction_id}:
    get:
      displayName: Get information for a specific transaction
      responses:
        200:
