#%RAML 1.0 SecurityScheme
type: x-jwt-token

describedBy:
  headers:
    Authorization: 
      type: string
      example: Bearer <token>
      description: The token has to follow a JWT pattern, know more at https://jwt.io/introduction
        