#%RAML 1.0 Library
usage: Use the following traits to define request and response headers and response status information

traits:
  cacheable: !include /exchange_modules/68ef9520-24e9-4cf2-b2f5-620025690913/training-cacheable-trait/1.0.1/Cacheable.raml
