#%RAML 1.0 NamedExample
CustomerExample:
  customerID: 8f19cb50-3f57-4d38
  firstName: Sarah
  lastName: Connor
  displayName: John Doe
  address: 
    addressLine1: 41 Lane
    addressLine2: Apt.#476
    city: Los Angeles
    state: Não sei
    zipCode: '89040010'
    country: United States
  phone: 415-879-0000
  email: johndoe@example.com
  ssn: 123-45-7890
  dateOfBirth: 1983-01-01
