#%RAML 1.0 NamedExample
value:
  customerID: 8f19cb50-3f57-4d38
  firstName: Sarah
  lastName: Connor
  displayName: John Doe
  address: 
    addressLine1: 41 Lane
    addressLine2: Apt.#476
    city: Los Angeles
    state: Não sei
    zipCode: '89040010'
    country: United States
  phone: 415-879-4475
  email: johndoe@example.com
  ssn: 143-45-7852
  dateOfBirth: 1985-05-02
