#%RAML 1.0 DocumentationItem
title: Getting Started with ACM Bank API
# if we use pipe |, then we can use markdown directly
content: |
  **ACM BANK** API offers _access_ to *customers*, acoounts and transactions data.

  So we offer these resourses:
    - Customers
    - Accounts
    - Transactions
